services:
  postgres:
    image: postgres:18
    container_name: trycore-evm-db
    environment:
      POSTGRES_USER: evm_user
      POSTGRES_PASSWORD: evm_password
      POSTGRES_DB: evm_db
    ports:
      - "5432:5432"
    volumes:
      - evm_postgres_data:/var/lib/postgresql

volumes:
  evm_postgres_data: