// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trycore.Evm.Infrastructure.Persistence;

#nullable disable

namespace Trycore.Evm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvmDbContext))]
    [Migration("20260703034305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trycore.Evm.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Trycore.Evm.Domain.Entities.ProjectActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_cost");

                    b.Property<decimal>("ActualProgressPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("actual_progress_percent");

                    b.Property<decimal>("Bac")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bac");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("PlannedProgressPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("planned_progress_percent");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_activities_project_id");

                    b.ToTable("activities", null, t =>
                        {
                            t.HasCheckConstraint("ck_activities_actual_cost", "actual_cost >= 0");

                            t.HasCheckConstraint("ck_activities_actual_percent", "actual_progress_percent >= 0 AND actual_progress_percent <= 100");

                            t.HasCheckConstraint("ck_activities_bac", "bac >= 0");

                            t.HasCheckConstraint("ck_activities_planned_percent", "planned_progress_percent >= 0 AND planned_progress_percent <= 100");
                        });
                });

            modelBuilder.Entity("Trycore.Evm.Domain.Entities.ProjectActivity", b =>
                {
                    b.HasOne("Trycore.Evm.Domain.Entities.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Trycore.Evm.Domain.Entities.Project", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
